# Generated by Django 4.0.4 on 2022-06-06 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_buyer_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Lahore', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(default='Faisal', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(default='+0000000000'),
        ),
    ]
