# Generated by Django 4.0.4 on 2022-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_buyer_purchase_date_alter_seller_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
    ]
